name: real
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  intl: ^0.18.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  uuid: ^4.5.1
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/image/nuclear.png
    - assets/fonts/Sarabun-Regular.ttf
