// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6TynQKO5VA39vWyYmYtMBNyTcfBNcJ4',
    appId: '1:922934292360:web:fc7f52abb6ee5f7ea0943d',
    messagingSenderId: '922934292360',
    projectId: 'flutterdb2025',
    authDomain: 'flutterdb2025.firebaseapp.com',
    storageBucket: 'flutterdb2025.firebasestorage.app',
    measurementId: 'G-G62CQ03PBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbbOaTVLaxFr-8seQu89OdF0pFZAQLics',
    appId: '1:922934292360:android:90e711ce8ee494e4a0943d',
    messagingSenderId: '922934292360',
    projectId: 'flutterdb2025',
    storageBucket: 'flutterdb2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe6TynQKO5VA39vWyYmYtMBNyTcfBNcJ4',
    appId: '1:922934292360:web:4d057dc7466f29aea0943d',
    messagingSenderId: '922934292360',
    projectId: 'flutterdb2025',
    authDomain: 'flutterdb2025.firebaseapp.com',
    storageBucket: 'flutterdb2025.firebasestorage.app',
    measurementId: 'G-BWTM0NEV85',
  );
}
